---
# handlers file for default/php7
- name: restart nginx
  become: true
  service: name=nginx state=restarted enabled=yes
- name: restart php-fpm
  become: true
  service: name=php7.4-fpm state=restarted enabled=yes
